version: '3'
services:
  marketplace-mongodb:
    image: mongo:3.6
    restart: always
    hostname: marketplace-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  marketplace-mariadb:
    image: mariadb
    restart: always
    hostname: marketplace-mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=marketplace
      - MYSQL_PASSWORD=marketplace
      - MYSQL_USER=marketplace

  marketplace-app:
    image: marketplace-app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - marketplace-mongodb
      - marketplace-mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://marketplace-mariadb:3306/marketplace?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=marketplace
      - SPRING_DATASOURCE_PASSWORD=marketplace
      - SPRING_DATA_MONGODB_URI=mongodb://marketplace-mongodb:27017/marketplace
